- docs/SQL Reference/09 Temporality.md
Writeup amended to reflect the Clause table
> Update 09 Temporality.md

- .github/workflows/code_form.yaml
- README.md
- opteryx/attribute_types.py
- opteryx/connection.py
- opteryx/connectors/aws_s3_connector.py
- opteryx/connectors/gcp_cloudstorage_connector.py
- opteryx/connectors/gcp_firestore_connector.py
- opteryx/connectors/sql_connector.py
- opteryx/exceptions.py
- opteryx/managers/cache/memcached.py
- opteryx/managers/kvstores/kv_firestore.py
- opteryx/third_party/travers/graph.py
- opteryx/utils/__init__.py
- opteryx/utils/arrow.py
- pyproject.toml
- tests/misc/test_connection.py
- tests/misc/test_connection_pandas.py
- tests/misc/test_documentation.py
- tests/misc/test_pandas_integration.py
> #housekeeping/1

- .github/workflows/secrets_scanning.yaml
- opteryx/__init__.py
- opteryx/components/binder.py
- opteryx/components/logical_planner.py
- opteryx/connectors/disk_connector.py
- opteryx/operators/aggregate_node.py
- opteryx/operators/join_node.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> 0.12.0 alpha.4

- opteryx/__version__.py
- opteryx/components/binder/binder.py
- opteryx/components/binder/binder_visitor.py
- opteryx/components/logical_planner_builders.py
- opteryx/managers/expression/formatter.py
- opteryx/models/__init__.py
- opteryx/models/logical_column.py
- tests/sql_battery/test_shapes_and_errors_battery.py
- tests/tools.py
> 0.12.0-alpha.7

- opteryx/components/binder/binder_visitor.py
> 🪲 aliases not handled correctly #1241

- opteryx/__version__.py
> 0.12.0-alpha.8

- .github/workflows/static_analysis.yaml
- opteryx/__init__.py
- opteryx/functions/other_functions.py
- opteryx/third_party/pyarrow_ops/helpers.py
- tests/misc/perftest_inner_hash.py
> 🪲 remove semgrep #1249

- opteryx/__version__.py
> 0.12.0-beta.1

- Cargo.toml
> Update pyo3 requirement from 0.19.1 to 0.20.0

- opteryx/__version__.py
> 0.12.0-beta.5

- opteryx/__init__.py
- opteryx/__version__.py
- opteryx/connectors/sql_connector.py
- tests/storage/test_sql_postgres.py
> 0.12.0-beta.6

- opteryx/__version__.py
- opteryx/components/heuristic_optimizer/__init__.py
- opteryx/components/heuristic_optimizer/strategies/predicate_pushdown.py
- opteryx/components/heuristic_optimizer/strategies/split_conjunctive_predicates.py
- opteryx/connectors/sql_connector.py
- opteryx/third_party/travers/graph.py
> 0.12.0-beta.7

- opteryx/__version__.py
- opteryx/components/heuristic_optimizer/__init__.py
- opteryx/components/heuristic_optimizer/strategies/predicate_pushdown.py
- opteryx/connectors/base/base_connector.py
- opteryx/connectors/sql_connector.py
- opteryx/cursor.py
- opteryx/models/node.py
- opteryx/third_party/travers/graph.py
- tests/requirements.txt
> 0.12.0-beta.8

- Makefile
- opteryx/__init__.py
- opteryx/__main__.py
- opteryx/__version__.py
- opteryx/components/binder/__init__.py
- opteryx/components/binder/binder.py
- opteryx/components/binder/binder_visitor.py
- opteryx/components/heuristic_optimizer/strategies/predicate_pushdown.py
- opteryx/components/logical_planner_builders.py
- opteryx/functions/__init__.py
- opteryx/managers/expression/formatter.py
- tests/plan_optimization/test_predicate_pushdown_postgres.py
- tests/sql_battery/test_shapes_and_errors_battery.py
- tests/sql_battery/test_sql_connector_battery.py
- tests/storage/test_sql_postgres.py
> 0.12.0-beta.11

- opteryx/__init__.py
- opteryx/__version__.py
> 0.12.0b124

- opteryx/__version__.py
- opteryx/connectors/capabilities/predicate_pushable.py
- opteryx/connectors/disk_connector.py
- opteryx/connectors/file_connector.py
- opteryx/connectors/gcp_cloudstorage_connector.py
- opteryx/third_party/pyarrow_ops/__init__.py
- opteryx/third_party/pyarrow_ops/helpers.py
- opteryx/third_party/pyarrow_ops/join.py
> 0.12.0 release

- opteryx/__version__.py
- opteryx/components/heuristic_optimizer/strategies/split_conjunctive_predicates.py
- opteryx/managers/expression/__init__.py
- tests/misc/test_expressions.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> #1355 Shortcut OR evaluations

- opteryx/__version__.py
- opteryx/connectors/gcp_cloudstorage_connector.py
> #1374 part3

- opteryx/__version__.py
> Opteryx Version 0.13.2

- opteryx/__version__.py
- opteryx/compiled/functions/ip_address.pyx
- opteryx/connectors/capabilities/partitionable.py
- opteryx/connectors/capabilities/predicate_pushable.py
- opteryx/connectors/mongodb_connector.py
- opteryx/functions/binary_operators.py
- opteryx/utils/arrow.py
> #1451 IP Containment Performance

- opteryx/__version__.py
- setup.py
> #1410 Remove pyarrow_ops compiler

- opteryx/__version__.py
- opteryx/functions/binary_operators.py
> #1481 - part 1

- opteryx/__version__.py
> Opteryx Version 0.13.4-alpha.376

- opteryx/__main__.py
- opteryx/__version__.py
> Opteryx Version 0.15.0-beta.493

- .github/workflows/release.yaml
- opteryx/__version__.py
> #housekeeping/3

- opteryx/__version__.py
- opteryx/utils/memory_view_stream.py
- tests/misc/test_mv_stream.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> HOUSEKEEPING

- opteryx/__version__.py
> ✨ push-based execution  #2061

- opteryx/__version__.py
> 0.19.0 release

- opteryx/__version__.py
- tests/query_execution/test_count_star.py
> Opteryx Version 0.19.1-alpha.974

- opteryx/__version__.py
- opteryx/operators/simple_aggregate_node.py
> ✨ speed up `COUNT_DISTINCT` #2276

- opteryx/__version__.py
- setup.py
> BUILD_ERRORS

- opteryx/__version__.py
- opteryx/compiled/joins/filter_join.pyx
- opteryx/compiled/joins/inner_join.pyx
- opteryx/compiled/structures/hash_table.pyx
- opteryx/connectors/iceberg_connector.py
> ✨ prefer cython hash

- opteryx/__version__.py
- opteryx/planner/optimizer/strategies/predicate_rewriter.py
- tests/plan_optimization/test_optimizations_invoked.py
> ✨ rewrite `CASE WHEN x IS NULL THEN y ELSE x` as `IFNULL(x, y)` #2293

- opteryx/__version__.py
- opteryx/connectors/sql_connector.py
- opteryx/planner/logical_planner/logical_planner.py
- tests/security/test_row_visibility_filters.py
> #2359 ✨ Visibility Filters for List Containment "AnyOps"

- Cargo.toml
- Makefile
- opteryx/__version__.py
- opteryx/functions/__init__.py
- opteryx/managers/expression/binary_operators.py
- opteryx/planner/__init__.py
- opteryx/planner/logical_planner/logical_planner.py
- opteryx/planner/logical_planner/logical_planner_builders.py
- opteryx/planner/sql_rewriter.py
- opteryx/planner/views/__init__.py
- src/lib.rs
- src/opteryx_dialect.rs
- tests/sql_battery/test_shapes_and_errors_battery.py
- tests/sql_battery/tests/opteryx-dialect.run_tests
- tests/sql_battery/tests/sqlectron.run_tests.disabled
- tests/sql_battery/tests/system.run_tests
> #2356 & #2376

- README.md
- opteryx/__version__.py
- opteryx/compiled/list_ops/list_regex_replace.pyx
- opteryx/connectors/capabilities/predicate_pushable.py
- opteryx/functions/string_functions.py
- opteryx/operators/base_plan_node.py
- opteryx/operators/simple_aggregate_and_group_node.py
- opteryx/planner/binder/binder_visitor.py
- opteryx/planner/logical_planner/logical_planner_builders.py
- tests/sql_battery/tests/feature_tests.run_tests
> #2388 [ClickBench] performance regression

- opteryx/__version__.py
> 0.20.0 release

- opteryx/__version__.py
- opteryx/compiled/structures/buffers.pxd
- opteryx/compiled/structures/buffers.pyx
- opteryx/compiled/structures/intbuffer.cpp
- opteryx/compiled/structures/intbuffer.h
- opteryx/functions/__init__.py
- opteryx/models/logical_column.py
- opteryx/operators/outer_join_node.py
- opteryx/planner/binder/binder.py
- opteryx/planner/logical_planner/logical_planner.py
- opteryx/planner/logical_planner/logical_planner_rewriter.py
- opteryx/planner/optimizer/strategies/optimization_strategy.py
- opteryx/planner/physical_planner.py
- setup.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> ✨ aggregate rewriter

- opteryx/__version__.py
- opteryx/compiled/list_ops/list_get_element.pyx
- opteryx/functions/__init__.py
- opteryx/operators/base_plan_node.py
- opteryx/virtual_datasets/no_table_data.py
- opteryx/virtual_datasets/planet_data.py
- setup.py
> #2259 🪲 High number of calls to Agg Operator

- opteryx/__version__.py
- opteryx/managers/execution/serial_engine.py
- opteryx/operators/base_plan_node.py
- opteryx/operators/exit_node.py
- opteryx/operators/explain_node.py
- opteryx/planner/logical_planner/logical_planner.py
- opteryx/utils/mermaid.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> ✨ plan to mermaid

- .github/workflows/regression_suite.yaml
- .github/workflows/regression_suite_arm.yaml
- .github/workflows/regression_suite_mac_ARM.yaml
- build-wheels.sh
- opteryx/__version__.py
> 🪲 build issues

- .github/workflows/regression_suite.yaml
- .github/workflows/regression_suite_arm.yaml
- .github/workflows/regression_suite_mac_ARM.yaml
- .gitignore
- Makefile
- opteryx/__version__.py
- opteryx/compiled/structures/bloom_filter.pxd
- opteryx/compiled/structures/bloom_filter.pyx
- opteryx/config.py
- opteryx/functions/date_functions.py
- opteryx/functions/other_functions.py
- opteryx/operators/inner_join_node.py
- opteryx/operators/outer_join_node.py
- opteryx/operators/read_node.py
- opteryx/planner/binder/binder.py
- opteryx/planner/optimizer/strategies/join_ordering.py
- opteryx/planner/optimizer/strategies/predicate_rewriter.py
- tests/fuzzing/test_sql_fuzzer_compare_engines.py
- tests/fuzzing/test_sql_fuzzer_connectors.py
- tests/plan_optimization/test_limit_pushdown_duckdb.py
- tests/requirements.txt
- tests/requirements_arm.txt
- tests/sql_battery/test_shapes_and_errors_battery.py
- tests/sql_battery/tests/types.run_tests
- tests/storage/test_sql_duckdb.py
- tests/tools.py
Fixes #2439
Fixes #2451
---
---
> ✨ rewrite COALESCE(x,y) to IFNULL(x,y)

- opteryx/__version__.py
- opteryx/compiled/structures/bloom_filter.pxd
- opteryx/compiled/structures/bloom_filter.pyx
- opteryx/operators/inner_join_node.py
- tests/misc/test_bloomfilter.py
- tests/tools.py
> #2453 Improvements to bloomfilter algo

- opteryx/__version__.py
- opteryx/compiled/table_ops/distinct.pyx
- opteryx/operators/distinct_node.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> #2456 Avoid Numpy in DISTINCT

- opteryx/__version__.py
- opteryx/compiled/aggregations/count_distinct.pyx
- opteryx/compiled/table_ops/distinct.pxd
- opteryx/operators/simple_aggregate_node.py
- tests/query_execution/test_agg_count_distinct.py
> ✨ rewrite simple aggs to use buffers #2457

- .github/workflows/regression_suite.yaml
- .github/workflows/regression_suite_arm.yaml
- .github/workflows/regression_suite_mac_ARM.yaml
- .gitignore
- Makefile
- opteryx/__version__.py
- opteryx/compiled/aggregations/count_distinct.pyx
- opteryx/compiled/table_ops/distinct.pxd
- opteryx/compiled/table_ops/distinct.pyx
- setup.py
- tests/sql_battery/tests/types.run_tests
- third_party/abseil/absl/base/c_header_test.c
> ✨ instead of building last of hashes, add to hashset

- opteryx/__version__.py
- opteryx/planner/optimizer/strategies/join_ordering.py
- tests/plan_optimization/test_optimizations_invoked.py
> #2463 [Optimizer] Smallest table to left in `INNER JOIN`

- opteryx/__version__.py
- opteryx/compiled/joins/cross_join.pyx
- opteryx/managers/expression/__init__.py
- opteryx/managers/expression/ops.py
> #2479 Reduce Literal Expansion

- opteryx/__version__.py
- opteryx/functions/other_functions.py
- opteryx/planner/optimizer/strategies/constant_folding.py
- opteryx/planner/optimizer/strategies/predicate_rewriter.py
- opteryx/utils/sql.py
- tests/sql_battery/test_shapes_and_errors_battery.py
Fixes #2514
Fixes #2468
---
---
> IFNULL assumes input is numpy array

- Cargo.toml
- opteryx/__version__.py
> Update pyo3 requirement from 0.23 to 0.24

- opteryx/__version__.py
- opteryx/compiled/list_ops/list_contains_any.pyx
- opteryx/planner/logical_planner/logical_planner_builders.py
> Remove prints

- opteryx/__version__.py
- opteryx/functions/other_functions.py
- opteryx/planner/optimizer/bench/cost_based_optimizer/predicate_ordering_genetic.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> Manually replace values to avoid multidimenstional array confusion in numpy #2614

- opteryx/__version__.py
- opteryx/compiled/joins/cross_join.pyx
> numpy object dtype definition incorrect in cross join #2636

- .github/workflows/on_push.yaml
- .github/workflows/version_comment.yaml
- opteryx/__version__.py
> [CI] Comment with build version

- opteryx/__version__.py
- opteryx/compiled/joins/inner_join.pyx
- opteryx/compiled/joins/outer_join.pyx
- opteryx/config.py
- opteryx/operators/cross_join_node.py
- opteryx/operators/inner_join_node.py
- opteryx/operators/outer_join_node.py
- opteryx/planner/optimizer/strategies/join_ordering.py
> JOIN CODE tidy up following changes #2626

- opteryx/__version__.py
- opteryx/compiled/table_ops/null_avoidant_ops.pyx
- tests/misc/test_null_bitmask.py
> chunk offset fix in null mask #2646

- opteryx/__version__.py
- opteryx/compiled/table_ops/distinct.pyx
- opteryx/compiled/table_ops/hash_ops.pyx
- opteryx/connectors/gcp_cloudstorage_connector.py
- opteryx/functions/string_functions.py
- opteryx/models/connection_state.py
> Linting fixes

- opteryx/__version__.py
- opteryx/connectors/gcp_cloudstorage_connector.py
- opteryx/operators/async_read_node.py
- opteryx/utils/file_decoders.py
- requirements.txt
> Review GCS connector #2659

- opteryx/__version__.py
- opteryx/connectors/capabilities/cacheable.py
> Fix cache oversize reporting #2661

- opteryx/__version__.py
- opteryx/connectors/gcp_cloudstorage_connector.py
> Restore GCS blob listing code #2667

- opteryx/__version__.py
- opteryx/compiled/structures/memory_pool.pyx
- opteryx/connectors/capabilities/cacheable.py
- opteryx/shared/buffer_pool.py
- opteryx/utils/file_decoders.py
- tests/misc/test_memory_pool.py
> Set latch on transfer between memory pools #2669

- build-wheels.sh
- opteryx/__version__.py
- requirements.txt
> fix build issues

- opteryx/__version__.py
- opteryx/compiled/structures/lru_k.pyx
- opteryx/connectors/aws_s3_connector.py
- opteryx/connectors/capabilities/cacheable.py
- opteryx/connectors/capabilities/statistics.py
- opteryx/models/relation_statistics.py
- opteryx/planner/binder/binder_visitor.py
- opteryx/shared/buffer_pool.py
- opteryx/shared/stats_cache.py
- setup.py
- tests/misc/test_lruk.py
- tests/storage/test_blob_gcs.py
- tests/storage/test_iceberg.py
> Enable stats and pushdowns on S3 #2692

- opteryx/__version__.py
- opteryx/connectors/capabilities/statistics.py
- opteryx/models/query_statistics.py
- opteryx/operators/async_read_node.py
> pruned blob statisitics

- opteryx/__version__.py
- opteryx/connectors/capabilities/statistics.py
- opteryx/connectors/disk_connector.py
- opteryx/connectors/file_connector.py
> Enable stats on disk connector #2697

- opteryx/__version__.py
- opteryx/compiled/list_ops/list_length.pyx
- opteryx/functions/__init__.py
- opteryx/managers/expression/ops.py
> Cythonize LENGTH function

- opteryx/__version__.py
- opteryx/compiled/list_ops/list_length.pyx
- opteryx/functions/__init__.py
- opteryx/functions/date_functions.py
- opteryx/managers/expression/__init__.py
- opteryx/managers/expression/binary_operators.py
- opteryx/managers/expression/ops.py
> performance tweaks to expression engine

- opteryx/__version__.py
- opteryx/compiled/list_ops/list_cast_int64_to_bytes.pyx
- opteryx/compiled/list_ops/list_cast_uint64_to_bytes.pyx
- opteryx/functions/__init__.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> custom INT to STRING casters

- opteryx/__version__.py
- opteryx/managers/expression/binary_operators.py
- opteryx/planner/optimizer/strategies/predicate_ordering.py
> reuse json parser

- .github/workflows/codeql.yaml
- opteryx/__version__.py
- opteryx/compiled/third_party/base64.pyx
- opteryx/third_party/alantsd/base64.pxd
- tests/functions/test_base64.py
- third_party/alantsd/base64.c
- third_party/alantsd/base64.h
> Improve base64 performance #2747

- opteryx/__version__.py
- opteryx/compiled/joins/inner_join.pyx
- opteryx/compiled/structures/bloom_filter.pyx
- opteryx/compiled/structures/memory_pool.pyx
- tests/misc/test_memory_pool.py
> Latches as ref counts #2751

- opteryx/__version__.py
- opteryx/compiled/structures/memory_pool.pyx
- opteryx/compiled/structures/relation_statistics.pyx
- tests/misc/test_relation_statistics.py
> improper encoding of UTF-8 strings #2756

- opteryx/__version__.py
- opteryx/cursor.py
- opteryx/planner/binder/binder_visitor.py
- opteryx/utils/arrow.py
> Result naming error #2725

- opteryx/__version__.py
- opteryx/compiled/table_ops/hash_ops.pyx
> Typo in Cython

- opteryx/__version__.py
- opteryx/compiled/list_ops/list_contains_all.pyx
- opteryx/functions/__init__.py
- opteryx/functions/other_functions.py
- opteryx/managers/expression/ops.py
- opteryx/planner/__init__.py
- opteryx/planner/binder/operator_map.py
- opteryx/planner/logical_planner/logical_planner.py
- opteryx/planner/logical_planner/logical_planner_builders.py
- opteryx/utils/dnf.py
- src/opteryx_dialect.rs
- tests/plan_optimization/test_visibility_filter_simplification.py
- tests/security/test_row_visibility_filters.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> Add initial DNF simplifier #2769

- opteryx/__version__.py
- opteryx/managers/expression/formatter.py
- opteryx/managers/expression/ops.py
- opteryx/planner/logical_planner/logical_planner.py
- opteryx/planner/optimizer/strategies/predicate_ordering.py
- opteryx/planner/optimizer/strategies/predicate_rewriter.py
- opteryx/planner/sql_rewriter.py
- opteryx/utils/dnf.py
- opteryx/utils/formatter.py
- tests/plan_optimization/test_visibility_filter_simplification.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> Simplify visibility filters

- opteryx/__version__.py
- opteryx/planner/logical_planner/logical_planner.py
- opteryx/utils/dnf.py
- tests/plan_optimization/test_optimizations_invoked.py
- tests/plan_optimization/test_visibility_filter_simplification.py
- tests/security/test_row_visibility_filters.py
> DNF simplifier edge cases #2776

- opteryx/__version__.py
- opteryx/planner/logical_planner/logical_planner.py
> release-0.25.1

- Makefile
- opteryx/__version__.py
- opteryx/connectors/sql_connector.py
- opteryx/managers/expression/__init__.py
- opteryx/utils/file_decoders.py
- pyproject.toml
- tests/sql_battery/test_null_semantics.py
- tests/sql_battery/test_shapes_and_errors_battery.py
> Replace pyarrow for parquet metadata #2804

- opteryx/__version__.py
- opteryx/utils/file_decoders.py
- pyproject.toml
- setup.py
> Use Rugo for Schemas

- opteryx/__version__.py
- pyproject.toml
> fix-version

- opteryx/__version__.py
- opteryx/operators/simple_aggregate_node.py
- pyproject.toml
- tests/sql_battery/test_shapes_and_errors_battery.py
> COUNT DISTINCT on empty results fails #2818

- opteryx/__version__.py
- opteryx/utils/file_decoders.py
- pyproject.toml
> [rugo] Use conditional metadata reading

- Makefile
- opteryx/__version__.py
- opteryx/compiled/list_ops/list_date_diff.pyx
- opteryx/functions/date_functions.py
- opteryx/utils/sql.py
- pyproject.toml
> refactor DATEDIFF function #2823
